#!/usr/bin/env bash
# Bootstrap the database for local development / CI.
#
# Four connections, four privilege levels (§8.6, §5):
#   superuser        creates roles and the database, then steps out
#   migration_owner  owns every table and runs alembic
#   cyberorch_app    the runtime role — owns nothing, cannot bypass RLS
#   registry_admin   the Engagement Manager — cyberorch_app plus write access
#                    to scope_registry and metadata_registry, nothing else
#
# Passwords are never hardcoded here. They are taken from the environment, or
# from a gitignored .env, or generated randomly on first run and written to
# .env. A checked-in default password is a credential in the repository even
# when it is "only for development", and it survives in the history after
# anyone deletes it.
#
# Two ways to reach the superuser, because CI and a workstation differ:
#   PGSUPER_MODE=peer  (default) su to the OS postgres user over the local socket
#   PGSUPER_MODE=tcp             connect as PGSUPER over TCP, e.g. a CI service
#                                container
# CI runs this same script rather than an equivalent-looking sequence of steps:
# a CI path that only resembles the developer path verifies the resemblance,
# not the thing developers actually run.
set -euo pipefail

DB_NAME="${DB_NAME:-cyberorch}"
PGSUPER="${PGSUPER:-postgres}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
PGSUPER_MODE="${PGSUPER_MODE:-peer}"
SKIP_SCHEMA_DUMP="${SKIP_SCHEMA_DUMP:-0}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$root/.env"

# shellcheck disable=SC1090
[ -f "$env_file" ] && set -a && . "$env_file" && set +a

gen_password() {
    python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
}

: "${MIGRATION_OWNER_PASSWORD:=$(gen_password)}"
: "${CYBERORCH_APP_PASSWORD:=$(gen_password)}"
: "${REGISTRY_ADMIN_PASSWORD:=$(gen_password)}"

# Run psql as the superuser. Arguments are passed through verbatim.
super_psql() {
    if [ "$PGSUPER_MODE" = "tcp" ]; then
        psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$PGSUPER" \
             -d "${PGSUPER_DB:-postgres}" "$@"
    else
        local quoted=()
        local arg
        for arg in "$@"; do quoted+=("$(printf '%q' "$arg")"); done
        su "$PGSUPER" -c "psql -v ON_ERROR_STOP=1 ${quoted[*]}"
    fi
}

# Same, but against $DB_NAME.
super_psql_db() {
    if [ "$PGSUPER_MODE" = "tcp" ]; then
        psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$PGSUPER" \
             -d "$DB_NAME" "$@"
    else
        local quoted=()
        local arg
        for arg in "$@"; do quoted+=("$(printf '%q' "$arg")"); done
        su "$PGSUPER" -c "psql -v ON_ERROR_STOP=1 -d $DB_NAME ${quoted[*]}"
    fi
}

echo "==> creating roles (superuser mode: $PGSUPER_MODE)"
super_psql \
    -v "migration_owner_password=$MIGRATION_OWNER_PASSWORD" \
    -v "cyberorch_app_password=$CYBERORCH_APP_PASSWORD" \
    -v "registry_admin_password=$REGISTRY_ADMIN_PASSWORD" \
    -f "$root/db/roles.sql" >/dev/null

echo "==> creating database $DB_NAME owned by migration_owner"
if ! super_psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
    super_psql -c "CREATE DATABASE $DB_NAME OWNER migration_owner" >/dev/null
fi

# cyberorch_app must not be able to create objects in public: an object it
# created would be an object it owns, and a table owner escapes RLS policies
# unless FORCE is set. Removing CREATE closes that route entirely.
super_psql_db -c "REVOKE CREATE ON SCHEMA public FROM PUBLIC" >/dev/null
super_psql_db -c "GRANT CREATE, USAGE ON SCHEMA public TO migration_owner" >/dev/null

echo "==> writing $env_file (gitignored)"
umask 077
cat > "$env_file" <<EOF
# Generated by scripts/init_db.sh. Gitignored — do not commit.
MIGRATION_OWNER_PASSWORD=${MIGRATION_OWNER_PASSWORD}
CYBERORCH_APP_PASSWORD=${CYBERORCH_APP_PASSWORD}
REGISTRY_ADMIN_PASSWORD=${REGISTRY_ADMIN_PASSWORD}
MIGRATION_DATABASE_URL=postgresql+psycopg://migration_owner:${MIGRATION_OWNER_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
DATABASE_URL=postgresql+psycopg://cyberorch_app:${CYBERORCH_APP_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
REGISTRY_ADMIN_DATABASE_URL=postgresql+psycopg://registry_admin:${REGISTRY_ADMIN_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
EOF
chmod 600 "$env_file"

echo "==> running migrations as migration_owner"
export MIGRATION_DATABASE_URL="postgresql+psycopg://migration_owner:${MIGRATION_OWNER_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
"$root/.venv/bin/alembic" -c "$root/alembic.ini" upgrade head

if [ "$SKIP_SCHEMA_DUMP" != "1" ]; then
    # Reference dump only. CI skips it: pg_dump client versions vary between
    # machines, and a version-dependent diff would be noise, not signal.
    echo "==> dumping reference schema to db/schema.sql"
    if [ "$PGSUPER_MODE" = "tcp" ]; then
        pg_dump --schema-only --no-owner --no-privileges \
                -h "$DB_HOST" -p "$DB_PORT" -U "$PGSUPER" -d "$DB_NAME" \
                > "$root/db/schema.sql.tmp" 2>/dev/null || true
    else
        su "$PGSUPER" -c "pg_dump --schema-only --no-owner --no-privileges -d $DB_NAME" \
                > "$root/db/schema.sql.tmp" 2>/dev/null || true
    fi
    if [ -s "$root/db/schema.sql.tmp" ]; then
        {
            echo "-- GENERATED FILE — do not edit."
            echo "-- Produced by scripts/init_db.sh from db/migrations. Reference only;"
            echo "-- grants and RLS live in the migration, which is the source of truth."
            cat "$root/db/schema.sql.tmp"
        } > "$root/db/schema.sql"
    fi
    rm -f "$root/db/schema.sql.tmp"
fi

echo "==> done. Connection strings are in .env; nothing was printed here."
