#!/usr/bin/env bash
# Bootstrap the database for local development / CI.
#
# Three connections, three privilege levels (§8.6):
#   superuser        creates roles and the database, then steps out
#   migration_owner  owns every table and runs alembic
#   cyberorch_app    the runtime role — owns nothing, cannot bypass RLS
#
# Passwords are never hardcoded here. They are taken from the environment, or
# from a gitignored .env, or generated randomly on first run and written to
# .env. A checked-in default password is a credential in the repository even
# when it is "only for development", and it survives in the history after
# anyone deletes it.
set -euo pipefail

DB_NAME="${DB_NAME:-cyberorch}"
PGSUPER="${PGSUPER:-postgres}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$root/.env"

# shellcheck disable=SC1090
[ -f "$env_file" ] && set -a && . "$env_file" && set +a

gen_password() {
    python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
}

: "${MIGRATION_OWNER_PASSWORD:=$(gen_password)}"
: "${CYBERORCH_APP_PASSWORD:=$(gen_password)}"

as_super() { su "$PGSUPER" -c "psql -v ON_ERROR_STOP=1 $*"; }

echo "==> creating roles"
su "$PGSUPER" -c "psql -v ON_ERROR_STOP=1 \
    -v migration_owner_password='$MIGRATION_OWNER_PASSWORD' \
    -v cyberorch_app_password='$CYBERORCH_APP_PASSWORD' \
    -f '$root/db/roles.sql'" >/dev/null

echo "==> creating database $DB_NAME owned by migration_owner"
if ! as_super "-tAc \"SELECT 1 FROM pg_database WHERE datname='$DB_NAME'\"" | grep -q 1; then
    as_super "-c \"CREATE DATABASE $DB_NAME OWNER migration_owner\"" >/dev/null
fi

# cyberorch_app must not be able to create objects in public: an object it
# created would be an object it owns, and a table owner escapes RLS policies
# unless FORCE is set. Removing CREATE closes that route entirely.
as_super "-d $DB_NAME -c \"REVOKE CREATE ON SCHEMA public FROM PUBLIC\"" >/dev/null
as_super "-d $DB_NAME -c \"GRANT CREATE, USAGE ON SCHEMA public TO migration_owner\"" >/dev/null

echo "==> writing $env_file (gitignored)"
umask 077
cat > "$env_file" <<EOF
# Generated by scripts/init_db.sh. Gitignored — do not commit.
MIGRATION_OWNER_PASSWORD=${MIGRATION_OWNER_PASSWORD}
CYBERORCH_APP_PASSWORD=${CYBERORCH_APP_PASSWORD}
MIGRATION_DATABASE_URL=postgresql+psycopg://migration_owner:${MIGRATION_OWNER_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
DATABASE_URL=postgresql+psycopg://cyberorch_app:${CYBERORCH_APP_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
EOF
chmod 600 "$env_file"

echo "==> running migrations as migration_owner"
export MIGRATION_DATABASE_URL="postgresql+psycopg://migration_owner:${MIGRATION_OWNER_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
"$root/.venv/bin/alembic" -c "$root/alembic.ini" upgrade head

echo "==> dumping reference schema to db/schema.sql"
su "$PGSUPER" -c "pg_dump --schema-only --no-owner --no-privileges -d $DB_NAME" \
    > "$root/db/schema.sql.tmp" 2>/dev/null || true
if [ -s "$root/db/schema.sql.tmp" ]; then
    {
        echo "-- GENERATED FILE — do not edit."
        echo "-- Produced by scripts/init_db.sh from db/migrations. Reference only;"
        echo "-- grants and RLS live in the migration, which is the source of truth."
        cat "$root/db/schema.sql.tmp"
    } > "$root/db/schema.sql"
fi
rm -f "$root/db/schema.sql.tmp"

echo "==> done. Connection strings are in .env; nothing was printed here."
